FROM    ubuntu:14.04

# Install Node.js and other dependencies
RUN apt-get update && \
    apt-get -y install curl && \
    curl -sL https://deb.nodesource.com/setup | sudo bash - && \
    apt-get -y install build-essential nodejs

# Bundle app source
COPY src /src

# Install app dependencies
RUN cd /src; npm install

EXPOSE  8080
# CMD ["npm", "start"]
CMD ["node", "/src/bin/www"]


